services:
  db:
    image: postgres:15.5
    env_file:
      - .env
    ports:
      - 5432:5432

  server:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./:/code/
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db