# Generated by Django 4.2.18 on 2025-01-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TD', 'To Do'), ('IN', 'In Progress'), ('Dn', 'Done')], default=False, max_length=20, verbose_name='Status')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.deck', verbose_name='Deck')),
            ],
        ),
    ]
