# Generated by Django 5.1.4 on 2025-01-14 22:16

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[('TD', 'to do'), ('IP', 'in progress'), ('DN', 'done')], default=False, verbose_name='Status')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='decks.task', verbose_name='Parent')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.tasksdeck', verbose_name='Deck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
