# Generated by Django 5.1.4 on 2025-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TD', 'to do'), ('IP', 'in progress'), ('DN', 'done')], default=False, max_length=20, verbose_name='Status'),
        ),
    ]
